name: jin_reflex_new
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  carousel_slider: ^5.1.1
  webview_flutter: ^4.13.0
  animate_do: ^4.2.0
  google_fonts: ^6.3.2
  http: ^1.6.0
  photo_view: ^0.15.0
  screenshot: ^3.0.0
  shared_preferences: ^2.5.3
  dio: ^5.9.0
  hexcolor: ^3.0.2
  flutter_riverpod: ^3.0.3
  url_launcher: ^6.3.2
  get: ^4.7.3
  html: ^0.15.6
  webview_flutter_android: ^4.10.1
  intl: ^0.20.2
  path_provider: ^2.1.5
  camera: ^0.11.2+1
  image_picker: ^1.2.1
  country_flags: ^4.1.1
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  flutter_image_compress: ^2.4.0
  country_state_city: ^0.1.6
  dropdown_search: ^5.0.6
  page_flip: ^0.2.5+1
  book_flip: ^1.0.0
  phonepe_payment_sdk: ^3.0.2
  crypto: ^3.0.7
  youtube_player_flutter: ^9.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

    - assets/images/jin_reflexo.png

    - assets/jinImages/


    - assets/foot-chart.html
    - assets/hand-chart.html
    - assets/hand-chart-right.html
    - assets/foot-chart-right.html

    - assets/button.json
    - assets/right_foot.json
    - assets/right_hand_btn.json
    - assets/left_hand_btn.json

    - assets/my-app.css
    - assets/my-app.js
    - assets/jquery.min.js
    - assets/ddimgtooltip1.js
    - assets/ddimgtooltip1.css
